const express = require('express');
const cors = require('cors');
const mysql = require('mysql2/promise');
const multer = require('multer');
const os = require('os');

const app = express();
app.use(cors());
app.use(express.json());

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 },
});

const dbConfig = {
  host: process.env.DB_HOST || 'localhost',
  user: process.env.DB_USER || 'ai_dashboard_user',
  password: process.env.DB_PASSWORD || 'change_me_password',
  database: process.env.DB_NAME || 'ai_dashboard_db',
  waitForConnections: true,
  connectionLimit: 10,
};

let pool;

async function getPool() {
  if (!pool) {
    pool = mysql.createPool(dbConfig);
  }
  return pool;
}

const ENTERPRISE_FUNCTIONS_SEED = [
  {
    name: 'Marketing & Sales',
    icon_name: 'Megaphone',
    color: 'border-l-blue-400',
    maturity: 'High',
    stat: 'Sales teams using LLM-assisted outreach report 40–50% higher pipeline conversion — Salesforce, 2024',
    uses: [
      '[LLM] Personalised content generation at scale — emails, ads, product descriptions drafted and varied per segment',
      '[ML] Lead scoring and propensity-to-buy models updated in real time from CRM and behavioural data',
      '[ML] Dynamic pricing and offer management — price optimisation models responding to demand signals',
      '[ASR + LLM] Conversation intelligence: call recordings transcribed (ASR) and analysed (LLM) to coach reps',
      '[ML] Campaign performance forecasting before launch — predicting conversion likelihood from historical patterns',
    ],
    sort_order: 1,
  },
  {
    name: 'Customer Service',
    icon_name: 'MessageSquare',
    color: 'border-l-emerald-400',
    maturity: 'High',
    stat: '35% reduction in cost-per-contact in large-scale deployments — Gartner, 2024',
    uses: [
      '[LLM + RAG] Tier-1 query resolution via LLM chatbot connected to knowledge base (RAG) — 50–70% deflection rates',
      '[LLM + RAG] Real-time agent assist — LLM surfaces relevant answers from docs during live calls',
      '[NLP] Sentiment analysis across all channels: NLP models score tone and urgency to flag at-risk customers',
      '[ASR + LLM] Automated case summarisation: ASR transcribes calls, LLM writes the case note and updates CRM',
      '[ML] Proactive outreach based on churn prediction models flagging at-risk customers before they contact you',
    ],
    sort_order: 2,
  },
  {
    name: 'Finance & Accounting',
    icon_name: 'BarChart2',
    color: 'border-l-amber-400',
    maturity: 'High',
    stat: '50% faster close cycles in finance teams using OCR + LLM tooling — McKinsey, 2024',
    uses: [
      '[OCR + ML] Automated three-way matching: OCR reads invoices; ML matches to PO and GR without manual keying',
      '[ML] Continuous fraud monitoring — unsupervised ML models detect anomalous transaction patterns in real time',
      '[LLM] Management commentary generated by LLM from structured actuals-vs-budget data — eliminates manual writing',
      '[LLM + NLP] Contract review: LLM reads documents and flags financial terms, obligations, and risk clauses',
      '[ML] Cash flow forecasting: ML regression models predict 30–90 day position from AR/AP and pipeline data',
    ],
    sort_order: 3,
  },
  {
    name: 'Supply Chain & Operations',
    icon_name: 'Link2',
    color: 'border-l-purple-400',
    maturity: 'Medium–High',
    stat: '15–20% inventory cost reduction through ML-optimised planning — WEF, 2025',
    uses: [
      '[ML] Demand forecasting: time-series ML models incorporate weather, events, and economic indicators',
      '[ML] Supplier risk monitoring: ML classifies risk signals and triggers early-warning alerts',
      '[ML] Predictive maintenance: ML models score equipment failure probability from sensor data (IoT)',
      '[ML] Route and inventory optimisation: combinatorial ML updated continuously from live operational data',
      '[CV] Quality control via computer vision (CV) cameras detecting defects on production lines in real time',
    ],
    sort_order: 4,
  },
  {
    name: 'HR & People',
    icon_name: 'Users',
    color: 'border-l-rose-400',
    maturity: 'Medium',
    stat: '35% reduction in time-to-hire using NLP + ML screening tools — Deloitte, 2024',
    uses: [
      '[NLP + ML] Applicant screening: NLP parses CVs; ML ranks candidates against structured role criteria',
      '[LLM + RAG] Personalised learning pathways: LLM recommends content based on role and assessed skill gaps',
      '[ML] Attrition prediction: ML models score flight risk from engagement signals and historical patterns',
      '[ML + NLP] Internal mobility matching: NLP + ML surface open roles to qualified internal candidates',
      '[LLM + RAG] Policy Q&A chatbot: LLM answers HR policy questions from the employee handbook via RAG',
    ],
    sort_order: 5,
  },
  {
    name: 'IT & Software Development',
    icon_name: 'Code2',
    color: 'border-l-slate-400',
    maturity: 'Very High',
    stat: 'Developers using LLM coding tools complete tasks 55% faster — GitHub, 2024',
    uses: [
      '[LLM] Code completion and generation (GitHub Copilot, Cursor) — adopted by 55%+ of enterprise dev teams',
      '[LLM] Automated test generation and vulnerability scanning from code context',
      '[LLM + ML] Incident response: LLM suggests root cause and remediation; ML anomaly detection triggers alerts',
      '[ML] AIOps: ML models detect infrastructure anomalies and forecast capacity needs',
      '[LLM + RAG] Knowledge base and documentation: LLM generates and updates docs from code and tickets (RAG)',
    ],
    sort_order: 6,
  },
];

async function runMigrations(db) {
  await db.query(`
    CREATE TABLE IF NOT EXISTS companies (
      id           INT AUTO_INCREMENT PRIMARY KEY,
      name         VARCHAR(200) NOT NULL,
      industry     VARCHAR(100),
      size         VARCHAR(50),
      contact_name VARCHAR(100),
      notes        TEXT,
      created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);

  const [aCols] = await db.query(`SHOW COLUMNS FROM assessments LIKE 'company_id'`);
  if (!aCols.length) {
    await db.query(`ALTER TABLE assessments ADD COLUMN company_id INT, ADD CONSTRAINT fk_assess_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL`);
  }

  const [rCols] = await db.query(`SHOW COLUMNS FROM roi_calculations LIKE 'company_id'`);
  if (!rCols.length) {
    await db.query(`ALTER TABLE roi_calculations ADD COLUMN company_id INT, ADD CONSTRAINT fk_roi_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL`);
  }

  await db.query(`
    CREATE TABLE IF NOT EXISTS enterprise_functions (
      id         INT AUTO_INCREMENT PRIMARY KEY,
      name       VARCHAR(255) NOT NULL,
      icon_name  VARCHAR(100) NOT NULL DEFAULT 'Megaphone',
      color      VARCHAR(100) NOT NULL DEFAULT 'border-l-blue-400',
      maturity   VARCHAR(50)  NOT NULL DEFAULT 'High',
      stat       TEXT,
      uses       JSON         NOT NULL,
      sort_order INT          DEFAULT 0,
      updated_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
  `);

  const [[{ count }]] = await db.query('SELECT COUNT(*) AS count FROM enterprise_functions');
  if (count === 0) {
    for (const fn of ENTERPRISE_FUNCTIONS_SEED) {
      await db.query(
        `INSERT INTO enterprise_functions (name, icon_name, color, maturity, stat, uses, sort_order)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        [fn.name, fn.icon_name, fn.color, fn.maturity, fn.stat, JSON.stringify(fn.uses), fn.sort_order]
      );
    }
    console.log('enterprise_functions seeded');
  }

  // ── database_platforms ────────────────────────────────────────────────────
  await db.query(`
    CREATE TABLE IF NOT EXISTS database_platforms (
      id              INT AUTO_INCREMENT PRIMARY KEY,
      name            VARCHAR(100) NOT NULL,
      tagline         TEXT,
      url             VARCHAR(255),
      logo_url        VARCHAR(500),
      screenshot_urls JSON,
      features        JSON,
      limitations     JSON,
      tags            JSON,
      color           VARCHAR(30) DEFAULT 'blue',
      sort_order      INT DEFAULT 0
    )
  `);

  const [[{ dbp_count }]] = await db.query('SELECT COUNT(*) AS dbp_count FROM database_platforms');
  if (dbp_count === 0) {
    const platforms = [
      {
        name: 'Baserow',
        tagline: 'Open source no-code database & Airtable alternative. Self-host via Docker or use Baserow cloud.',
        url: 'https://baserow.io',
        logo_url: 'https://raw.githubusercontent.com/bram2w/baserow/master/web-frontend/modules/core/static/img/logo.svg',
        screenshot_urls: JSON.stringify([
          'https://baserow.io/img/baserow-screenshot-grid.png',
          'https://baserow.io/img/baserow-screenshot-gallery.png',
        ]),
        features: JSON.stringify([
          'Grid, gallery, kanban, calendar, and form views',
          'REST API auto-generated for every table and field',
          'Role-based access: admin, member, viewer per workspace',
          'Webhooks triggered on row create/update/delete',
          'Formula fields, lookup fields, link-to-table relations',
          'Docker self-host or Baserow cloud — unlimited rows self-hosted',
        ]),
        limitations: JSON.stringify([
          'Free cloud plan capped at 5,000 rows and 5 GB storage',
          'Row-level access rules (filter-based permissions) are premium',
          'Public shared views are view-only — no per-viewer identity filter',
          'Automations (save-triggered workflows) are premium only',
          'No SSO / SAML on free tier — email auth only',
          'Password-protected shared views require a premium plan',
        ]),
        tags: JSON.stringify(['self-hosted', 'open-source', 'docker', 'rest-api', 'no-code']),
        color: 'blue',
        sort_order: 1,
      },
      {
        name: 'NocoDB',
        tagline: 'Turns any MySQL, PostgreSQL, or SQLite database into a smart spreadsheet UI with APIs and views.',
        url: 'https://nocodb.com',
        logo_url: 'https://raw.githubusercontent.com/nocodb/nocodb/develop/packages/nc-gui/assets/img/icons/512x512-trans.png',
        screenshot_urls: JSON.stringify([
          'https://raw.githubusercontent.com/nocodb/nocodb/develop/.github/assets/screenshots/22.png',
          'https://raw.githubusercontent.com/nocodb/nocodb/develop/.github/assets/screenshots/23.png',
        ]),
        features: JSON.stringify([
          'Connects to MySQL, PostgreSQL, SQLite, MariaDB — your existing DB',
          'Grid, gallery, form, kanban, and map views',
          'REST & GraphQL API auto-generated per table',
          'Shared views with optional password protection',
          'Webhook triggers on record create/update/delete',
          'Self-host via Docker, AGPL free and open source',
        ]),
        limitations: JSON.stringify([
          'Row-level access only via view filters — no per-user identity routing',
          'No column-level hiding per user on free tier',
          'Password-protected views use one shared password for all viewers',
          'Save-triggered conditional actions require enterprise plan',
          'Cloud attachment storage limited on free plan',
          'No built-in audit log on open source version',
        ]),
        tags: JSON.stringify(['self-hosted', 'open-source', 'postgresql', 'mysql', 'graphql', 'no-code']),
        color: 'violet',
        sort_order: 2,
      },
      {
        name: 'Grist',
        tagline: 'Spreadsheet meets database — Python formula columns, granular access rules, and sharable views.',
        url: 'https://getgrist.com',
        logo_url: 'https://raw.githubusercontent.com/gristlabs/grist-core/main/static/icons/GristLogo.png',
        screenshot_urls: JSON.stringify([
          'https://raw.githubusercontent.com/gristlabs/grist-core/main/static/img/docs/newsletters/2021-09/kanban.png',
          'https://www.getgrist.com/wp-content/uploads/2023/10/grist-access-rules.png',
        ]),
        features: JSON.stringify([
          'Python-powered formula columns — full NumPy/Pandas access',
          'Granular access rules at row, column, and table level',
          'Link & filter views — each user sees only their data slice',
          'Custom widgets (maps, charts) embeddable per page',
          'Version history and document snapshots',
          'Self-host via Docker (AGPL), free and open source',
        ]),
        limitations: JSON.stringify([
          'Free cloud plan: 5 documents, 5,000 rows per document',
          'No SSO on free or free-plus plans',
          'Column-level access rules are available but complex to configure',
          'External webhooks on save require the Business plan',
          'No native mobile app',
          'Per-user row filtering requires careful formula-based access rule setup',
        ]),
        tags: JSON.stringify(['self-hosted', 'open-source', 'python', 'access-rules', 'no-code']),
        color: 'emerald',
        sort_order: 3,
      },
      {
        name: 'Teable',
        tagline: 'Postgres-native, high-performance Airtable alternative — handles millions of rows with real-time collaboration.',
        url: 'https://teable.io',
        logo_url: 'https://raw.githubusercontent.com/teableio/teable/develop/apps/nextjs-app/public/favicon/android-chrome-192x192.png',
        screenshot_urls: JSON.stringify([
          'https://raw.githubusercontent.com/teableio/teable/develop/.github/screenshots/table-view.png',
          'https://raw.githubusercontent.com/teableio/teable/develop/.github/screenshots/kanban-view.png',
        ]),
        features: JSON.stringify([
          'Built directly on PostgreSQL — millions of rows without performance degradation',
          'Real-time collaboration with low latency multiplayer editing',
          'Grid, gallery, kanban, calendar, and form views',
          'REST API and plugin system for extensibility',
          'Self-hostable under AGPL, actively developed',
          'AI field assistant (beta) for formula suggestions',
        ]),
        limitations: JSON.stringify([
          'Relatively new product — some enterprise features still in development',
          'No column-level access control on free tier yet',
          'Automations are limited on the free self-hosted version',
          'No SSO / SAML on free plan',
          'Public shared views are read-only with no per-viewer row filtering',
          'Password-protected shared views not available on free tier',
        ]),
        tags: JSON.stringify(['self-hosted', 'open-source', 'postgresql', 'real-time', 'no-code']),
        color: 'amber',
        sort_order: 4,
      },
      {
        name: 'Mathesar',
        tagline: 'Web interface for PostgreSQL — schema design, data editing, and filtered views without writing SQL.',
        url: 'https://mathesar.org',
        logo_url: 'https://raw.githubusercontent.com/mathesar-foundation/mathesar/develop/mathesar_ui/src/assets/images/mathesar_logo.svg',
        screenshot_urls: JSON.stringify([
          'https://mathesar.org/assets/img/home/hero-screenshot.png',
          'https://mathesar.org/assets/img/features/table-screenshot.png',
        ]),
        features: JSON.stringify([
          'Direct PostgreSQL interface — no proprietary data layer or migration required',
          'Table editor, data explorer, and schema designer in the browser',
          'Role-based access control matching native PostgreSQL roles',
          'Shareable filtered views per user group',
          'Works with existing databases — connect and start immediately',
          'Fully self-hosted, free and open source (GPL)',
        ]),
        limitations: JSON.stringify([
          'No cloud hosted option — must self-host on your own infrastructure',
          'No built-in automations or webhook triggers',
          'Only grid/table view — no kanban, gallery, or calendar views',
          'No native form builder for public data collection',
          'Column-level access requires PostgreSQL role configuration by a DBA',
          'No password-protected public sharing links',
        ]),
        tags: JSON.stringify(['self-hosted', 'open-source', 'postgresql', 'sql', 'low-code']),
        color: 'rose',
        sort_order: 5,
      },
    ];

    for (const p of platforms) {
      await db.query(
        `INSERT INTO database_platforms (name, tagline, url, logo_url, screenshot_urls, features, limitations, tags, color, sort_order)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [p.name, p.tagline, p.url, p.logo_url, p.screenshot_urls, p.features, p.limitations, p.tags, p.color, p.sort_order]
      );
    }
    console.log('database_platforms seeded');
  }

  // ── lab_gallery ───────────────────────────────────────────────────────────
  await db.query(`
    CREATE TABLE IF NOT EXISTS lab_gallery (
      id          INT AUTO_INCREMENT PRIMARY KEY,
      name        VARCHAR(255) NOT NULL,
      mime_type   VARCHAR(100) NOT NULL DEFAULT 'image/jpeg',
      file_data   LONGBLOB NOT NULL,
      file_size   INT,
      comment     TEXT,
      created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
  `);
}

// ── Health ────────────────────────────────────────────────────────────────────
app.get('/api/health', async (req, res) => {
  try {
    const db = await getPool();
    await db.query('SELECT 1');
    res.json({ status: 'ok', database: 'connected' });
  } catch (err) {
    res.status(500).json({ status: 'error', message: err.message });
  }
});

// ── Companies ─────────────────────────────────────────────────────────────────
app.get('/api/companies', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM companies ORDER BY name');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/companies', async (req, res) => {
  const { name, industry, size, contact_name, notes } = req.body;
  if (!name) return res.status(400).json({ error: 'name is required' });
  try {
    const db = await getPool();
    const [result] = await db.query(
      'INSERT INTO companies (name, industry, size, contact_name, notes) VALUES (?, ?, ?, ?, ?)',
      [name, industry || null, size || null, contact_name || null, notes || null]
    );
    const [rows] = await db.query('SELECT * FROM companies WHERE id = ?', [result.insertId]);
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/companies/:id', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM companies WHERE id = ?', [req.params.id]);
    if (!rows.length) return res.status(404).json({ error: 'Not found' });
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Assessments ───────────────────────────────────────────────────────────────
app.post('/api/assessments', async (req, res) => {
  const { answers, score, stage, stageLabel, recommendedPages, company_id } = req.body;
  try {
    const db = await getPool();
    const [result] = await db.query(
      'INSERT INTO assessments (answers, score, stage, stage_label, recommended_pages, company_id) VALUES (?, ?, ?, ?, ?, ?)',
      [JSON.stringify(answers), score, stage, stageLabel, JSON.stringify(recommendedPages), company_id || null]
    );
    res.json({ id: result.insertId, score, stage, stageLabel, recommendedPages });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/assessments/:id', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM assessments WHERE id = ?', [req.params.id]);
    if (!rows.length) return res.status(404).json({ error: 'Not found' });
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── ROI ───────────────────────────────────────────────────────────────────────
app.post('/api/roi', async (req, res) => {
  const {
    roleName, hoursPerTask, frequencyPerMonth, hourlyRate,
    aiUpliftPct, toolCostMonthly, annualSaving, paybackMonths, roi24m, roi36m, company_id,
  } = req.body;
  try {
    const db = await getPool();
    const [result] = await db.query(
      `INSERT INTO roi_calculations
       (role_name, hours_per_task, frequency_per_month, hourly_rate,
        ai_uplift_pct, tool_cost_monthly, annual_saving, payback_months, roi_24m, roi_36m, company_id)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [roleName, hoursPerTask, frequencyPerMonth, hourlyRate,
       aiUpliftPct, toolCostMonthly, annualSaving, paybackMonths, roi24m, roi36m, company_id || null]
    );
    res.json({ id: result.insertId });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/roi/models', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM roi_models ORDER BY id');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Enterprise Functions ──────────────────────────────────────────────────────
app.get('/api/enterprise/functions', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM enterprise_functions ORDER BY sort_order');
    const parsed = rows.map(r => ({ ...r, uses: typeof r.uses === 'string' ? JSON.parse(r.uses) : r.uses }));
    res.json(parsed);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.put('/api/enterprise/functions/:id', async (req, res) => {
  const { id } = req.params;
  const { name, icon_name, color, maturity, stat, uses } = req.body;
  if (!name || !Array.isArray(uses)) return res.status(400).json({ error: 'name and uses (array) are required' });
  try {
    const db = await getPool();
    await db.query(
      `UPDATE enterprise_functions SET name=?, icon_name=?, color=?, maturity=?, stat=?, uses=? WHERE id=?`,
      [name, icon_name, color, maturity, stat, JSON.stringify(uses), id]
    );
    const [[row]] = await db.query('SELECT * FROM enterprise_functions WHERE id=?', [id]);
    if (!row) return res.status(404).json({ error: 'Not found' });
    res.json({ ...row, uses: typeof row.uses === 'string' ? JSON.parse(row.uses) : row.uses });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Server network info (for QR code LAN URL) ────────────────────────────────
app.get('/api/server-ip', (req, res) => {
  // LAN_IP env var takes priority — set it in .env to a fixed LAN address
  // so the QR code always points to the right host regardless of which
  // network interface the server happens to enumerate first.
  const envIp = process.env.LAN_IP;
  let ips;
  if (envIp) {
    ips = [envIp];
  } else {
    const ifaces = os.networkInterfaces();
    ips = Object.values(ifaces).flat()
      .filter(i => i.family === 'IPv4' && !i.internal)
      .map(i => i.address);
  }
  const origin = req.headers.origin || '';
  const frontendPort = origin.match(/:(\d+)/)?.[1] || '3001';
  res.json({ ips, frontendPort: Number(frontendPort) });
});

// ── Lab: Database Platforms ───────────────────────────────────────────────────
app.get('/api/lab/database-platforms', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM database_platforms ORDER BY sort_order');
    const parsed = rows.map(r => ({
      ...r,
      screenshot_urls: typeof r.screenshot_urls === 'string' ? JSON.parse(r.screenshot_urls) : r.screenshot_urls,
      features:        typeof r.features === 'string'        ? JSON.parse(r.features)        : r.features,
      limitations:     typeof r.limitations === 'string'     ? JSON.parse(r.limitations)     : r.limitations,
      tags:            typeof r.tags === 'string'             ? JSON.parse(r.tags)            : r.tags,
    }));
    res.json(parsed);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Lab: Gallery ─────────────────────────────────────────────────────────────

// Upload image
app.post('/api/lab/gallery', upload.single('file'), async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ error: 'No file provided' });
    const { originalname, mimetype, buffer, size } = req.file;
    const name = req.body.name || originalname;
    const db = await getPool();
    const [result] = await db.query(
      'INSERT INTO lab_gallery (name, mime_type, file_data, file_size) VALUES (?, ?, ?, ?)',
      [name, mimetype, buffer, size]
    );
    res.json({ id: result.insertId, name, mime_type: mimetype, file_size: size, comment: '', created_at: new Date().toISOString() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// List gallery (no binary data)
app.get('/api/lab/gallery', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query(
      'SELECT id, name, mime_type, file_size, comment, created_at, updated_at FROM lab_gallery ORDER BY created_at DESC'
    );
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Serve image binary
app.get('/api/lab/gallery/:id/image', async (req, res) => {
  try {
    const db = await getPool();
    const [[row]] = await db.query('SELECT mime_type, file_data FROM lab_gallery WHERE id = ?', [req.params.id]);
    if (!row) return res.status(404).json({ error: 'Not found' });
    res.set('Content-Type', row.mime_type);
    res.set('Cache-Control', 'public, max-age=86400');
    res.send(row.file_data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Update name / comment
app.put('/api/lab/gallery/:id', async (req, res) => {
  try {
    const { name, comment } = req.body;
    const db = await getPool();
    if (name !== undefined) await db.query('UPDATE lab_gallery SET name = ? WHERE id = ?', [name, req.params.id]);
    if (comment !== undefined) await db.query('UPDATE lab_gallery SET comment = ? WHERE id = ?', [comment, req.params.id]);
    const [[row]] = await db.query(
      'SELECT id, name, mime_type, file_size, comment, created_at, updated_at FROM lab_gallery WHERE id = ?',
      [req.params.id]
    );
    res.json(row || { error: 'Not found' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Delete
app.delete('/api/lab/gallery/:id', async (req, res) => {
  try {
    const db = await getPool();
    await db.query('DELETE FROM lab_gallery WHERE id = ?', [req.params.id]);
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Start ─────────────────────────────────────────────────────────────────────
const PORT = process.env.PORT || 3002;
app.listen(PORT, async () => {
  console.log(`Backend running on port ${PORT}`);
  try {
    const db = await getPool();
    await runMigrations(db);
    console.log('Database migrations complete');
  } catch (err) {
    console.error('Migration error:', err.message);
  }
});
