const express = require('express');
const cors = require('cors');
const mysql = require('mysql2/promise');

const app = express();
app.use(cors());
app.use(express.json());

const dbConfig = {
  host: process.env.DB_HOST || 'localhost',
  user: process.env.DB_USER || 'ai_dashboard_user',
  password: process.env.DB_PASSWORD || 'change_me_password',
  database: process.env.DB_NAME || 'ai_dashboard_db',
  waitForConnections: true,
  connectionLimit: 10,
};

let pool;

async function getPool() {
  if (!pool) {
    pool = mysql.createPool(dbConfig);
  }
  return pool;
}

const ENTERPRISE_FUNCTIONS_SEED = [
  {
    name: 'Marketing & Sales',
    icon_name: 'Megaphone',
    color: 'border-l-blue-400',
    maturity: 'High',
    stat: 'Sales teams using LLM-assisted outreach report 40–50% higher pipeline conversion — Salesforce, 2024',
    uses: [
      '[LLM] Personalised content generation at scale — emails, ads, product descriptions drafted and varied per segment',
      '[ML] Lead scoring and propensity-to-buy models updated in real time from CRM and behavioural data',
      '[ML] Dynamic pricing and offer management — price optimisation models responding to demand signals',
      '[ASR + LLM] Conversation intelligence: call recordings transcribed (ASR) and analysed (LLM) to coach reps',
      '[ML] Campaign performance forecasting before launch — predicting conversion likelihood from historical patterns',
    ],
    sort_order: 1,
  },
  {
    name: 'Customer Service',
    icon_name: 'MessageSquare',
    color: 'border-l-emerald-400',
    maturity: 'High',
    stat: '35% reduction in cost-per-contact in large-scale deployments — Gartner, 2024',
    uses: [
      '[LLM + RAG] Tier-1 query resolution via LLM chatbot connected to knowledge base (RAG) — 50–70% deflection rates',
      '[LLM + RAG] Real-time agent assist — LLM surfaces relevant answers from docs during live calls',
      '[NLP] Sentiment analysis across all channels: NLP models score tone and urgency to flag at-risk customers',
      '[ASR + LLM] Automated case summarisation: ASR transcribes calls, LLM writes the case note and updates CRM',
      '[ML] Proactive outreach based on churn prediction models flagging at-risk customers before they contact you',
    ],
    sort_order: 2,
  },
  {
    name: 'Finance & Accounting',
    icon_name: 'BarChart2',
    color: 'border-l-amber-400',
    maturity: 'High',
    stat: '50% faster close cycles in finance teams using OCR + LLM tooling — McKinsey, 2024',
    uses: [
      '[OCR + ML] Automated three-way matching: OCR reads invoices; ML matches to PO and GR without manual keying',
      '[ML] Continuous fraud monitoring — unsupervised ML models detect anomalous transaction patterns in real time',
      '[LLM] Management commentary generated by LLM from structured actuals-vs-budget data — eliminates manual writing',
      '[LLM + NLP] Contract review: LLM reads documents and flags financial terms, obligations, and risk clauses',
      '[ML] Cash flow forecasting: ML regression models predict 30–90 day position from AR/AP and pipeline data',
    ],
    sort_order: 3,
  },
  {
    name: 'Supply Chain & Operations',
    icon_name: 'Link2',
    color: 'border-l-purple-400',
    maturity: 'Medium–High',
    stat: '15–20% inventory cost reduction through ML-optimised planning — WEF, 2025',
    uses: [
      '[ML] Demand forecasting: time-series ML models incorporate weather, events, and economic indicators',
      '[ML] Supplier risk monitoring: ML classifies risk signals and triggers early-warning alerts',
      '[ML] Predictive maintenance: ML models score equipment failure probability from sensor data (IoT)',
      '[ML] Route and inventory optimisation: combinatorial ML updated continuously from live operational data',
      '[CV] Quality control via computer vision (CV) cameras detecting defects on production lines in real time',
    ],
    sort_order: 4,
  },
  {
    name: 'HR & People',
    icon_name: 'Users',
    color: 'border-l-rose-400',
    maturity: 'Medium',
    stat: '35% reduction in time-to-hire using NLP + ML screening tools — Deloitte, 2024',
    uses: [
      '[NLP + ML] Applicant screening: NLP parses CVs; ML ranks candidates against structured role criteria',
      '[LLM + RAG] Personalised learning pathways: LLM recommends content based on role and assessed skill gaps',
      '[ML] Attrition prediction: ML models score flight risk from engagement signals and historical patterns',
      '[ML + NLP] Internal mobility matching: NLP + ML surface open roles to qualified internal candidates',
      '[LLM + RAG] Policy Q&A chatbot: LLM answers HR policy questions from the employee handbook via RAG',
    ],
    sort_order: 5,
  },
  {
    name: 'IT & Software Development',
    icon_name: 'Code2',
    color: 'border-l-slate-400',
    maturity: 'Very High',
    stat: 'Developers using LLM coding tools complete tasks 55% faster — GitHub, 2024',
    uses: [
      '[LLM] Code completion and generation (GitHub Copilot, Cursor) — adopted by 55%+ of enterprise dev teams',
      '[LLM] Automated test generation and vulnerability scanning from code context',
      '[LLM + ML] Incident response: LLM suggests root cause and remediation; ML anomaly detection triggers alerts',
      '[ML] AIOps: ML models detect infrastructure anomalies and forecast capacity needs',
      '[LLM + RAG] Knowledge base and documentation: LLM generates and updates docs from code and tickets (RAG)',
    ],
    sort_order: 6,
  },
];

async function runMigrations(db) {
  await db.query(`
    CREATE TABLE IF NOT EXISTS companies (
      id           INT AUTO_INCREMENT PRIMARY KEY,
      name         VARCHAR(200) NOT NULL,
      industry     VARCHAR(100),
      size         VARCHAR(50),
      contact_name VARCHAR(100),
      notes        TEXT,
      created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);

  const [aCols] = await db.query(`SHOW COLUMNS FROM assessments LIKE 'company_id'`);
  if (!aCols.length) {
    await db.query(`ALTER TABLE assessments ADD COLUMN company_id INT, ADD CONSTRAINT fk_assess_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL`);
  }

  const [rCols] = await db.query(`SHOW COLUMNS FROM roi_calculations LIKE 'company_id'`);
  if (!rCols.length) {
    await db.query(`ALTER TABLE roi_calculations ADD COLUMN company_id INT, ADD CONSTRAINT fk_roi_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL`);
  }

  await db.query(`
    CREATE TABLE IF NOT EXISTS enterprise_functions (
      id         INT AUTO_INCREMENT PRIMARY KEY,
      name       VARCHAR(255) NOT NULL,
      icon_name  VARCHAR(100) NOT NULL DEFAULT 'Megaphone',
      color      VARCHAR(100) NOT NULL DEFAULT 'border-l-blue-400',
      maturity   VARCHAR(50)  NOT NULL DEFAULT 'High',
      stat       TEXT,
      uses       JSON         NOT NULL,
      sort_order INT          DEFAULT 0,
      updated_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
  `);

  const [[{ count }]] = await db.query('SELECT COUNT(*) AS count FROM enterprise_functions');
  if (count === 0) {
    for (const fn of ENTERPRISE_FUNCTIONS_SEED) {
      await db.query(
        `INSERT INTO enterprise_functions (name, icon_name, color, maturity, stat, uses, sort_order)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        [fn.name, fn.icon_name, fn.color, fn.maturity, fn.stat, JSON.stringify(fn.uses), fn.sort_order]
      );
    }
    console.log('enterprise_functions seeded');
  }
}

// ── Health ────────────────────────────────────────────────────────────────────
app.get('/api/health', async (req, res) => {
  try {
    const db = await getPool();
    await db.query('SELECT 1');
    res.json({ status: 'ok', database: 'connected' });
  } catch (err) {
    res.status(500).json({ status: 'error', message: err.message });
  }
});

// ── Companies ─────────────────────────────────────────────────────────────────
app.get('/api/companies', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM companies ORDER BY name');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/companies', async (req, res) => {
  const { name, industry, size, contact_name, notes } = req.body;
  if (!name) return res.status(400).json({ error: 'name is required' });
  try {
    const db = await getPool();
    const [result] = await db.query(
      'INSERT INTO companies (name, industry, size, contact_name, notes) VALUES (?, ?, ?, ?, ?)',
      [name, industry || null, size || null, contact_name || null, notes || null]
    );
    const [rows] = await db.query('SELECT * FROM companies WHERE id = ?', [result.insertId]);
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/companies/:id', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM companies WHERE id = ?', [req.params.id]);
    if (!rows.length) return res.status(404).json({ error: 'Not found' });
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Assessments ───────────────────────────────────────────────────────────────
app.post('/api/assessments', async (req, res) => {
  const { answers, score, stage, stageLabel, recommendedPages, company_id } = req.body;
  try {
    const db = await getPool();
    const [result] = await db.query(
      'INSERT INTO assessments (answers, score, stage, stage_label, recommended_pages, company_id) VALUES (?, ?, ?, ?, ?, ?)',
      [JSON.stringify(answers), score, stage, stageLabel, JSON.stringify(recommendedPages), company_id || null]
    );
    res.json({ id: result.insertId, score, stage, stageLabel, recommendedPages });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/assessments/:id', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM assessments WHERE id = ?', [req.params.id]);
    if (!rows.length) return res.status(404).json({ error: 'Not found' });
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── ROI ───────────────────────────────────────────────────────────────────────
app.post('/api/roi', async (req, res) => {
  const {
    roleName, hoursPerTask, frequencyPerMonth, hourlyRate,
    aiUpliftPct, toolCostMonthly, annualSaving, paybackMonths, roi24m, roi36m, company_id,
  } = req.body;
  try {
    const db = await getPool();
    const [result] = await db.query(
      `INSERT INTO roi_calculations
       (role_name, hours_per_task, frequency_per_month, hourly_rate,
        ai_uplift_pct, tool_cost_monthly, annual_saving, payback_months, roi_24m, roi_36m, company_id)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [roleName, hoursPerTask, frequencyPerMonth, hourlyRate,
       aiUpliftPct, toolCostMonthly, annualSaving, paybackMonths, roi24m, roi36m, company_id || null]
    );
    res.json({ id: result.insertId });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/roi/models', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM roi_models ORDER BY id');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Enterprise Functions ──────────────────────────────────────────────────────
app.get('/api/enterprise/functions', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM enterprise_functions ORDER BY sort_order');
    const parsed = rows.map(r => ({ ...r, uses: typeof r.uses === 'string' ? JSON.parse(r.uses) : r.uses }));
    res.json(parsed);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.put('/api/enterprise/functions/:id', async (req, res) => {
  const { id } = req.params;
  const { name, icon_name, color, maturity, stat, uses } = req.body;
  if (!name || !Array.isArray(uses)) return res.status(400).json({ error: 'name and uses (array) are required' });
  try {
    const db = await getPool();
    await db.query(
      `UPDATE enterprise_functions SET name=?, icon_name=?, color=?, maturity=?, stat=?, uses=? WHERE id=?`,
      [name, icon_name, color, maturity, stat, JSON.stringify(uses), id]
    );
    const [[row]] = await db.query('SELECT * FROM enterprise_functions WHERE id=?', [id]);
    if (!row) return res.status(404).json({ error: 'Not found' });
    res.json({ ...row, uses: typeof row.uses === 'string' ? JSON.parse(row.uses) : row.uses });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Start ─────────────────────────────────────────────────────────────────────
const PORT = process.env.PORT || 3002;
app.listen(PORT, async () => {
  console.log(`Backend running on port ${PORT}`);
  try {
    const db = await getPool();
    await runMigrations(db);
    console.log('Database migrations complete');
  } catch (err) {
    console.error('Migration error:', err.message);
  }
});
