const express = require('express');
const cors = require('cors');
const mysql = require('mysql2/promise');
const multer = require('multer');
const os = require('os');
const path = require('path');
const { PDFDocument, PDFName, PDFString, PDFNumber, rgb } = require('pdf-lib');
const { v4: uuidv4 } = require('uuid');

const app = express();
app.use(cors());
app.use(express.json({ limit: '20mb' }));

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 },
});

const dbConfig = {
  host: process.env.DB_HOST || 'localhost',
  user: process.env.DB_USER || 'ai_dashboard_user',
  password: process.env.DB_PASSWORD || 'change_me_password',
  database: process.env.DB_NAME || 'ai_dashboard_db',
  waitForConnections: true,
  connectionLimit: 10,
};

let pool;

async function getPool() {
  if (!pool) {
    pool = mysql.createPool(dbConfig);
  }
  return pool;
}

const ENTERPRISE_FUNCTIONS_SEED = [
  {
    name: 'Marketing & Sales',
    icon_name: 'Megaphone',
    color: 'border-l-blue-400',
    maturity: 'High',
    stat: 'Sales teams using LLM-assisted outreach report 40–50% higher pipeline conversion — Salesforce, 2024',
    uses: [
      '[LLM] Personalised content generation at scale — emails, ads, product descriptions drafted and varied per segment',
      '[ML] Lead scoring and propensity-to-buy models updated in real time from CRM and behavioural data',
      '[ML] Dynamic pricing and offer management — price optimisation models responding to demand signals',
      '[ASR + LLM] Conversation intelligence: call recordings transcribed (ASR) and analysed (LLM) to coach reps',
      '[ML] Campaign performance forecasting before launch — predicting conversion likelihood from historical patterns',
    ],
    sort_order: 1,
  },
  {
    name: 'Customer Service',
    icon_name: 'MessageSquare',
    color: 'border-l-emerald-400',
    maturity: 'High',
    stat: '35% reduction in cost-per-contact in large-scale deployments — Gartner, 2024',
    uses: [
      '[LLM + RAG] Tier-1 query resolution via LLM chatbot connected to knowledge base (RAG) — 50–70% deflection rates',
      '[LLM + RAG] Real-time agent assist — LLM surfaces relevant answers from docs during live calls',
      '[NLP] Sentiment analysis across all channels: NLP models score tone and urgency to flag at-risk customers',
      '[ASR + LLM] Automated case summarisation: ASR transcribes calls, LLM writes the case note and updates CRM',
      '[ML] Proactive outreach based on churn prediction models flagging at-risk customers before they contact you',
    ],
    sort_order: 2,
  },
  {
    name: 'Finance & Accounting',
    icon_name: 'BarChart2',
    color: 'border-l-amber-400',
    maturity: 'High',
    stat: '50% faster close cycles in finance teams using OCR + LLM tooling — McKinsey, 2024',
    uses: [
      '[OCR + ML] Automated three-way matching: OCR reads invoices; ML matches to PO and GR without manual keying',
      '[ML] Continuous fraud monitoring — unsupervised ML models detect anomalous transaction patterns in real time',
      '[LLM] Management commentary generated by LLM from structured actuals-vs-budget data — eliminates manual writing',
      '[LLM + NLP] Contract review: LLM reads documents and flags financial terms, obligations, and risk clauses',
      '[ML] Cash flow forecasting: ML regression models predict 30–90 day position from AR/AP and pipeline data',
    ],
    sort_order: 3,
  },
  {
    name: 'Supply Chain & Operations',
    icon_name: 'Link2',
    color: 'border-l-purple-400',
    maturity: 'Medium–High',
    stat: '15–20% inventory cost reduction through ML-optimised planning — WEF, 2025',
    uses: [
      '[ML] Demand forecasting: time-series ML models incorporate weather, events, and economic indicators',
      '[ML] Supplier risk monitoring: ML classifies risk signals and triggers early-warning alerts',
      '[ML] Predictive maintenance: ML models score equipment failure probability from sensor data (IoT)',
      '[ML] Route and inventory optimisation: combinatorial ML updated continuously from live operational data',
      '[CV] Quality control via computer vision (CV) cameras detecting defects on production lines in real time',
    ],
    sort_order: 4,
  },
  {
    name: 'HR & People',
    icon_name: 'Users',
    color: 'border-l-rose-400',
    maturity: 'Medium',
    stat: '35% reduction in time-to-hire using NLP + ML screening tools — Deloitte, 2024',
    uses: [
      '[NLP + ML] Applicant screening: NLP parses CVs; ML ranks candidates against structured role criteria',
      '[LLM + RAG] Personalised learning pathways: LLM recommends content based on role and assessed skill gaps',
      '[ML] Attrition prediction: ML models score flight risk from engagement signals and historical patterns',
      '[ML + NLP] Internal mobility matching: NLP + ML surface open roles to qualified internal candidates',
      '[LLM + RAG] Policy Q&A chatbot: LLM answers HR policy questions from the employee handbook via RAG',
    ],
    sort_order: 5,
  },
  {
    name: 'IT & Software Development',
    icon_name: 'Code2',
    color: 'border-l-slate-400',
    maturity: 'Very High',
    stat: 'Developers using LLM coding tools complete tasks 55% faster — GitHub, 2024',
    uses: [
      '[LLM] Code completion and generation (GitHub Copilot, Cursor) — adopted by 55%+ of enterprise dev teams',
      '[LLM] Automated test generation and vulnerability scanning from code context',
      '[LLM + ML] Incident response: LLM suggests root cause and remediation; ML anomaly detection triggers alerts',
      '[ML] AIOps: ML models detect infrastructure anomalies and forecast capacity needs',
      '[LLM + RAG] Knowledge base and documentation: LLM generates and updates docs from code and tickets (RAG)',
    ],
    sort_order: 6,
  },
];

async function runMigrations(db) {
  await db.query(`
    CREATE TABLE IF NOT EXISTS companies (
      id           INT AUTO_INCREMENT PRIMARY KEY,
      name         VARCHAR(200) NOT NULL,
      industry     VARCHAR(100),
      size         VARCHAR(50),
      contact_name VARCHAR(100),
      notes        TEXT,
      created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);

  const [aCols] = await db.query(`SHOW COLUMNS FROM assessments LIKE 'company_id'`);
  if (!aCols.length) {
    await db.query(`ALTER TABLE assessments ADD COLUMN company_id INT, ADD CONSTRAINT fk_assess_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL`);
  }

  const [rCols] = await db.query(`SHOW COLUMNS FROM roi_calculations LIKE 'company_id'`);
  if (!rCols.length) {
    await db.query(`ALTER TABLE roi_calculations ADD COLUMN company_id INT, ADD CONSTRAINT fk_roi_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL`);
  }

  await db.query(`
    CREATE TABLE IF NOT EXISTS enterprise_functions (
      id         INT AUTO_INCREMENT PRIMARY KEY,
      name       VARCHAR(255) NOT NULL,
      icon_name  VARCHAR(100) NOT NULL DEFAULT 'Megaphone',
      color      VARCHAR(100) NOT NULL DEFAULT 'border-l-blue-400',
      maturity   VARCHAR(50)  NOT NULL DEFAULT 'High',
      stat       TEXT,
      uses       JSON         NOT NULL,
      sort_order INT          DEFAULT 0,
      updated_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
  `);

  const [[{ count }]] = await db.query('SELECT COUNT(*) AS count FROM enterprise_functions');
  if (count === 0) {
    for (const fn of ENTERPRISE_FUNCTIONS_SEED) {
      await db.query(
        `INSERT INTO enterprise_functions (name, icon_name, color, maturity, stat, uses, sort_order)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        [fn.name, fn.icon_name, fn.color, fn.maturity, fn.stat, JSON.stringify(fn.uses), fn.sort_order]
      );
    }
    console.log('enterprise_functions seeded');
  }

  // ── database_platforms ────────────────────────────────────────────────────
  await db.query(`
    CREATE TABLE IF NOT EXISTS database_platforms (
      id              INT AUTO_INCREMENT PRIMARY KEY,
      name            VARCHAR(100) NOT NULL,
      tagline         TEXT,
      url             VARCHAR(255),
      logo_url        VARCHAR(500),
      screenshot_urls JSON,
      features        JSON,
      limitations     JSON,
      tags            JSON,
      color           VARCHAR(30) DEFAULT 'blue',
      badge           VARCHAR(100),
      sort_order      INT DEFAULT 0
    )
  `);

  // Add badge column to existing installations
  const [badgeCols] = await db.query(`SHOW COLUMNS FROM database_platforms LIKE 'badge'`);
  if (!badgeCols.length) {
    await db.query(`ALTER TABLE database_platforms ADD COLUMN badge VARCHAR(100) AFTER color`);
  }

  const [[{ dbp_count }]] = await db.query('SELECT COUNT(*) AS dbp_count FROM database_platforms');
  if (dbp_count === 0) {
    const platforms = [
      {
        name: 'Baserow',
        tagline: 'Open source no-code database & Airtable alternative. Self-host via Docker or use Baserow cloud.',
        url: 'https://baserow.io',
        logo_url: 'https://raw.githubusercontent.com/bram2w/baserow/master/web-frontend/modules/core/static/img/logo.svg',
        screenshot_urls: JSON.stringify([
          'https://baserow.io/img/baserow-screenshot-grid.png',
          'https://baserow.io/img/baserow-screenshot-gallery.png',
        ]),
        features: JSON.stringify([
          'Grid, gallery, kanban, calendar, and form views',
          'REST API auto-generated for every table and field',
          'Role-based access: admin, member, viewer per workspace',
          'Webhooks triggered on row create/update/delete',
          'Formula fields, lookup fields, link-to-table relations',
          'Docker self-host or Baserow cloud — unlimited rows self-hosted',
        ]),
        limitations: JSON.stringify([
          'Free cloud plan capped at 5,000 rows and 5 GB storage',
          'Row-level access rules (filter-based permissions) are premium',
          'Public shared views are view-only — no per-viewer identity filter',
          'Automations (save-triggered workflows) are premium only',
          'No SSO / SAML on free tier — email auth only',
          'Password-protected shared views require a premium plan',
        ]),
        tags: JSON.stringify(['self-hosted', 'open-source', 'docker', 'rest-api', 'no-code']),
        color: 'blue',
        sort_order: 1,
      },
      {
        name: 'NocoDB',
        tagline: 'Turns any MySQL, PostgreSQL, or SQLite database into a smart spreadsheet UI with APIs and views.',
        url: 'https://nocodb.com',
        logo_url: 'https://raw.githubusercontent.com/nocodb/nocodb/develop/packages/nc-gui/assets/img/icons/512x512-trans.png',
        screenshot_urls: JSON.stringify([
          'https://raw.githubusercontent.com/nocodb/nocodb/develop/.github/assets/screenshots/22.png',
          'https://raw.githubusercontent.com/nocodb/nocodb/develop/.github/assets/screenshots/23.png',
        ]),
        features: JSON.stringify([
          'Connects to MySQL, PostgreSQL, SQLite, MariaDB — your existing DB',
          'Grid, gallery, form, kanban, and map views',
          'REST & GraphQL API auto-generated per table',
          'Shared views with optional password protection',
          'Webhook triggers on record create/update/delete',
          'Self-host via Docker, AGPL free and open source',
        ]),
        limitations: JSON.stringify([
          'Row-level access only via view filters — no per-user identity routing',
          'No column-level hiding per user on free tier',
          'Password-protected views use one shared password for all viewers',
          'Save-triggered conditional actions require enterprise plan',
          'Cloud attachment storage limited on free plan',
          'No built-in audit log on open source version',
        ]),
        tags: JSON.stringify(['self-hosted', 'open-source', 'postgresql', 'mysql', 'graphql', 'no-code']),
        color: 'violet',
        sort_order: 2,
      },
      {
        name: 'Grist',
        tagline: 'Spreadsheet meets database — Python formula columns, granular access rules, and sharable views.',
        url: 'https://getgrist.com',
        logo_url: 'https://raw.githubusercontent.com/gristlabs/grist-core/main/static/icons/GristLogo.png',
        screenshot_urls: JSON.stringify([
          'https://raw.githubusercontent.com/gristlabs/grist-core/main/static/img/docs/newsletters/2021-09/kanban.png',
          'https://www.getgrist.com/wp-content/uploads/2023/10/grist-access-rules.png',
        ]),
        features: JSON.stringify([
          'Python-powered formula columns — full NumPy/Pandas access',
          'Granular access rules at row, column, and table level',
          'Link & filter views — each user sees only their data slice',
          'Custom widgets (maps, charts) embeddable per page',
          'Version history and document snapshots',
          'Self-host via Docker (AGPL), free and open source',
        ]),
        limitations: JSON.stringify([
          'Free cloud plan: 5 documents, 5,000 rows per document',
          'No SSO on free or free-plus plans',
          'Column-level access rules are available but complex to configure',
          'External webhooks on save require the Business plan',
          'No native mobile app',
          'Per-user row filtering requires careful formula-based access rule setup',
        ]),
        tags: JSON.stringify(['self-hosted', 'open-source', 'python', 'access-rules', 'no-code']),
        color: 'emerald',
        sort_order: 3,
      },
      {
        name: 'Teable',
        tagline: 'Postgres-native, high-performance Airtable alternative — handles millions of rows with real-time collaboration.',
        url: 'https://teable.io',
        logo_url: 'https://raw.githubusercontent.com/teableio/teable/develop/apps/nextjs-app/public/favicon/android-chrome-192x192.png',
        screenshot_urls: JSON.stringify([
          'https://raw.githubusercontent.com/teableio/teable/develop/.github/screenshots/table-view.png',
          'https://raw.githubusercontent.com/teableio/teable/develop/.github/screenshots/kanban-view.png',
        ]),
        features: JSON.stringify([
          'Built directly on PostgreSQL — millions of rows without performance degradation',
          'Real-time collaboration with low latency multiplayer editing',
          'Grid, gallery, kanban, calendar, and form views',
          'REST API and plugin system for extensibility',
          'Self-hostable under AGPL, actively developed',
          'AI field assistant (beta) for formula suggestions',
        ]),
        limitations: JSON.stringify([
          'Relatively new product — some enterprise features still in development',
          'No column-level access control on free tier yet',
          'Automations are limited on the free self-hosted version',
          'No SSO / SAML on free plan',
          'Public shared views are read-only with no per-viewer row filtering',
          'Password-protected shared views not available on free tier',
        ]),
        tags: JSON.stringify(['self-hosted', 'open-source', 'postgresql', 'real-time', 'no-code']),
        color: 'amber',
        sort_order: 4,
      },
      {
        name: 'Mathesar',
        tagline: 'Web interface for PostgreSQL — schema design, data editing, and filtered views without writing SQL.',
        url: 'https://mathesar.org',
        logo_url: 'https://raw.githubusercontent.com/mathesar-foundation/mathesar/develop/mathesar_ui/src/assets/images/mathesar_logo.svg',
        screenshot_urls: JSON.stringify([
          'https://mathesar.org/assets/img/home/hero-screenshot.png',
          'https://mathesar.org/assets/img/features/table-screenshot.png',
        ]),
        features: JSON.stringify([
          'Direct PostgreSQL interface — no proprietary data layer or migration required',
          'Table editor, data explorer, and schema designer in the browser',
          'Role-based access control matching native PostgreSQL roles',
          'Shareable filtered views per user group',
          'Works with existing databases — connect and start immediately',
          'Fully self-hosted, free and open source (GPL)',
        ]),
        limitations: JSON.stringify([
          'No cloud hosted option — must self-host on your own infrastructure',
          'No built-in automations or webhook triggers',
          'Only grid/table view — no kanban, gallery, or calendar views',
          'No native form builder for public data collection',
          'Column-level access requires PostgreSQL role configuration by a DBA',
          'No password-protected public sharing links',
        ]),
        tags: JSON.stringify(['self-hosted', 'open-source', 'postgresql', 'sql', 'low-code']),
        color: 'rose',
        badge: null,
        sort_order: 5,
      },
    ];

    for (const p of platforms) {
      await db.query(
        `INSERT INTO database_platforms (name, tagline, url, logo_url, screenshot_urls, features, limitations, tags, color, badge, sort_order)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [p.name, p.tagline, p.url, p.logo_url, p.screenshot_urls, p.features, p.limitations, p.tags, p.color, p.badge, p.sort_order]
      );
    }
    console.log('database_platforms seeded');
  }

  // Insert new platforms added after initial seed (idempotent by name)
  const newPlatforms = [
    {
      name: 'Budibase',
      tagline: 'Drag-and-drop internal tool builder — connect any data source and ship forms, dashboards, and workflows fast.',
      url: 'https://budibase.com',
      logo_url: 'https://raw.githubusercontent.com/Budibase/budibase/develop/.github/bb-emblem.svg',
      screenshot_urls: JSON.stringify([]),
      features: JSON.stringify([
        'Drag-and-drop UI builder — tables, forms, charts, kanban, no CSS required',
        'Connects to PostgreSQL, MySQL, MongoDB, REST APIs, Google Sheets, S3',
        'Built-in role-based access control — free on self-hosted, unlimited users',
        'Automation workflows triggered on data changes or custom schedules',
        'Self-host via Docker or Kubernetes under AGPLv3 at no cost',
        'Component library with 50+ pre-built blocks for rapid prototyping',
      ]),
      limitations: JSON.stringify([
        'Cloud free plan limited to 5 users and 100 automation runs/month',
        'No column-level field permissions — access scoped via data source queries',
        'Outputs responsive web apps only — no native iOS/Android app builder',
        'Visual query builder cannot handle complex multi-step SQL CTEs',
        'Branding and white-label features locked to Enterprise plan',
        'Audit logs and enforced SSO are cloud Enterprise only',
      ]),
      tags: JSON.stringify(['self-hosted', 'open-source', 'internal-tools', 'low-code', 'agpl']),
      color: 'indigo',
      badge: null,
      sort_order: 6,
    },
    {
      name: 'PocketBase',
      tagline: 'Single-file Go backend with embedded SQLite, built-in Admin UI, realtime subscriptions, and auth — MIT licensed.',
      url: 'https://pocketbase.io',
      logo_url: 'https://pocketbase.io/images/logo.svg',
      screenshot_urls: JSON.stringify([]),
      features: JSON.stringify([
        'Single binary under 30MB — DB, auth, REST API, realtime, and Admin UI in one file',
        'MIT license — no restrictions on commercial use, distribution, or modification',
        'Built-in Admin UI for managing collections, users, rules, and settings',
        'Realtime subscriptions via SSE — instant data push without polling',
        'Auth: email/password, OAuth2 (Google, GitHub, Discord, etc.), anonymous',
        'JavaScript and Dart SDKs with community SDKs for Python, .NET, and more',
      ]),
      limitations: JSON.stringify([
        'SQLite-only — not designed for multi-server horizontal scaling',
        'No built-in multi-tenant row isolation without custom hooks',
        'Admin UI is minimal — no formula fields, computed columns, or rich views',
        'No built-in job scheduler or workflow automation engine',
        'Manual backup/restore — no automated snapshot schedule out of the box',
        'Complex queries require custom hooks or external tooling',
      ]),
      tags: JSON.stringify(['mit-license', 'self-hosted', 'sqlite', 'realtime', 'go', 'backend']),
      color: 'cyan',
      badge: '⭐ AWESOME — MIT',
      sort_order: 7,
    },
    {
      name: 'Frappe Framework',
      tagline: 'Schema-driven full-stack Python framework — define a DocType once and get form, list, API, and permissions automatically.',
      url: 'https://frappeframework.com',
      logo_url: 'https://raw.githubusercontent.com/frappe/frappe/develop/frappe/public/images/frappe-framework-logo.svg',
      screenshot_urls: JSON.stringify([]),
      features: JSON.stringify([
        'Schema-driven DocType system — define once, auto-generates form, list, REST API, and permissions',
        'MIT license — unrestricted commercial and SaaS use',
        'Role and user permission model at DocType and document level',
        'REST API auto-generated per DocType with filtering, sorting, and pagination',
        'Foundation for ERPNext — battle-tested at enterprise scale in production',
        'Built-in scheduler, job queue, email sending, and websocket events',
      ]),
      limitations: JSON.stringify([
        'Large open issue backlog on GitHub — slower bug triage and community-driven fixes',
        'Steep learning curve — custom DocTypes require Python development skills',
        'Framework opinionates heavily: routing, form rendering, and ORM are tightly coupled',
        'Full-text search requires separate Elasticsearch add-on configuration',
        'Modern Frappe UI patterns differ from standard React — framework-specific learning',
        'Docker self-host setup is more complex than single-binary alternatives',
      ]),
      tags: JSON.stringify(['mit-license', 'python', 'self-hosted', 'erp', 'open-source']),
      color: 'orange',
      badge: '⚠ Many Open Issues — MIT',
      sort_order: 8,
    },
    {
      name: 'Appwrite',
      tagline: 'Open-source backend-as-a-service — auth, databases, storage, functions, and messaging in a single self-hosted API.',
      url: 'https://appwrite.io',
      logo_url: 'https://raw.githubusercontent.com/appwrite/appwrite/main/public/images/appwrite.svg',
      screenshot_urls: JSON.stringify([]),
      features: JSON.stringify([
        'Backend-as-a-service: auth, databases, storage, functions, messaging — single API',
        'BSD 3-Clause license — permissive for commercial and open-source products',
        'SDKs for 10+ platforms: web, Flutter, iOS, Android, React Native, Node.js',
        'Auth: email/password, magic link, OAuth2, phone OTP, and anonymous sessions',
        'Realtime database subscriptions and serverless Functions with multiple runtimes',
        'Self-host via Docker Compose — single command launches the full backend stack',
      ]),
      limitations: JSON.stringify([
        'Large open issue backlog on GitHub — some long-standing bugs awaiting resolution',
        'Free cloud plan: 75K monthly active users, 2GB storage, 750K function executions',
        'No relational joins in Appwrite Databases — document/collection model only',
        'Function cold starts can be slow on low-resource self-hosted instances',
        'Complex attribute index requirements can complicate filtering at scale',
        'No built-in admin table data editor — manage data via Console UI or API only',
      ]),
      tags: JSON.stringify(['bsd-3-clause', 'self-hosted', 'backend-as-a-service', 'auth', 'storage']),
      color: 'rose',
      badge: '⚠ Many Open Issues — BSD 3-Clause',
      sort_order: 9,
    },
    {
      name: 'Windmill',
      tagline: 'Script runtime and workflow orchestrator for Python, TypeScript, Go, and Bash — with a low-code app builder included.',
      url: 'https://windmill.dev',
      logo_url: 'https://raw.githubusercontent.com/windmill-labs/windmill/main/frontend/src/lib/assets/windmill.svg',
      screenshot_urls: JSON.stringify([]),
      features: JSON.stringify([
        'Script runtime for Python, TypeScript, Go, Bash — sandboxed workers with dependency auto-install',
        'Visual workflow builder (DAG flows) connecting scripts, integrations, and approvals',
        'Low-code app builder for internal dashboards with reactive, composable components',
        'Granular RBAC and workspace isolation — safe for multi-team self-hosted deployments',
        '10,000 free executions/month on cloud — generous for most small team workloads',
        'Active development with frequent releases and a responsive maintainer team',
      ]),
      limitations: JSON.stringify([
        'AGPL3 license — SaaS products incorporating Windmill must open-source their modifications',
        'Learning curve: scripts, flows, and apps are three distinct concepts to master together',
        'No built-in relational database view — scripts must query and transform external DBs',
        'Complex fan-out flows with many branches can be difficult to debug and trace',
        'SSO, audit logs, and dedicated worker pools require the Enterprise license',
        'Community-only support on free tier — no SLA or guaranteed response time',
      ]),
      tags: JSON.stringify(['agpl3', 'self-hosted', 'workflow-automation', 'scripts', 'low-code']),
      color: 'violet',
      badge: '✓ Recommended — AGPL3',
      sort_order: 10,
    },
  ];

  for (const p of newPlatforms) {
    const [[{ nameExists }]] = await db.query(
      'SELECT COUNT(*) AS nameExists FROM database_platforms WHERE name = ?', [p.name]
    );
    if (!nameExists) {
      await db.query(
        `INSERT INTO database_platforms (name, tagline, url, logo_url, screenshot_urls, features, limitations, tags, color, badge, sort_order)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [p.name, p.tagline, p.url, p.logo_url, p.screenshot_urls, p.features, p.limitations, p.tags, p.color, p.badge, p.sort_order]
      );
      console.log(`database_platforms: inserted ${p.name}`);
    }
  }

  // ── lab_gallery ───────────────────────────────────────────────────────────
  await db.query(`
    CREATE TABLE IF NOT EXISTS lab_gallery (
      id          INT AUTO_INCREMENT PRIMARY KEY,
      name        VARCHAR(255) NOT NULL,
      mime_type   VARCHAR(100) NOT NULL DEFAULT 'image/jpeg',
      file_data   LONGBLOB NOT NULL,
      file_size   INT,
      comment     TEXT,
      created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
  `);

  // ── lab_excalidraw ────────────────────────────────────────────────────────
  await db.query(`
    CREATE TABLE IF NOT EXISTS lab_excalidraw (
      id          INT AUTO_INCREMENT PRIMARY KEY,
      name        VARCHAR(255) NOT NULL DEFAULT 'Untitled Drawing',
      scene_data  LONGTEXT,
      thumbnail   MEDIUMTEXT,
      created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
  `);

  // ── planning_doc ──────────────────────────────────────────────────────────
  await db.query(`
    CREATE TABLE IF NOT EXISTS planning_doc (
      id         INT AUTO_INCREMENT PRIMARY KEY,
      content    LONGTEXT NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
  `);
  const [[{ pd_count }]] = await db.query('SELECT COUNT(*) AS pd_count FROM planning_doc');
  if (pd_count === 0) {
    const defaultContent = `this is the first server right & proves that you are connected.`;
    await db.query('INSERT INTO planning_doc (content) VALUES (?)', [defaultContent]);
    console.log('planning_doc seeded');
  }

  // ── pdf_files ────────────────────────────────────────────────────────────
  await db.query(`
    CREATE TABLE IF NOT EXISTS pdf_files (
      id           VARCHAR(36) PRIMARY KEY,
      original_name VARCHAR(255) NOT NULL,
      stored_name  VARCHAR(255) NOT NULL,
      size         INT NOT NULL,
      file_data    LONGBLOB,
      created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);
  await db.query('ALTER TABLE pdf_files ADD COLUMN IF NOT EXISTS file_data LONGBLOB');

  // ── pdf_annotations ──────────────────────────────────────────────────────
  await db.query(`
    CREATE TABLE IF NOT EXISTS pdf_annotations (
      id           INT AUTO_INCREMENT PRIMARY KEY,
      pdf_id       VARCHAR(36) NOT NULL,
      type         VARCHAR(30) NOT NULL,
      page_index   INT NOT NULL DEFAULT 0,
      x            FLOAT NOT NULL DEFAULT 0,
      y            FLOAT NOT NULL DEFAULT 0,
      width        FLOAT NOT NULL DEFAULT 0,
      height       FLOAT NOT NULL DEFAULT 0,
      color        VARCHAR(20) DEFAULT 'yellow',
      content      TEXT,
      quoted_text  TEXT,
      created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX (pdf_id)
    )
  `);

  // ── pdf_fabric_data ──────────────────────────────────────────────────────
  await db.query(`
    CREATE TABLE IF NOT EXISTS pdf_fabric_data (
      id         INT AUTO_INCREMENT PRIMARY KEY,
      file_id    VARCHAR(36) NOT NULL,
      pages_json MEDIUMTEXT,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UNIQUE KEY uq_file (file_id)
    )
  `);

}

// ── Health ────────────────────────────────────────────────────────────────────
app.get('/api/health', async (req, res) => {
  try {
    const db = await getPool();
    await db.query('SELECT 1');
    res.json({ status: 'ok', database: 'connected' });
  } catch (err) {
    res.status(500).json({ status: 'error', message: err.message });
  }
});

// ── Companies ─────────────────────────────────────────────────────────────────
app.get('/api/companies', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM companies ORDER BY name');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/companies', async (req, res) => {
  const { name, industry, size, contact_name, notes } = req.body;
  if (!name) return res.status(400).json({ error: 'name is required' });
  try {
    const db = await getPool();
    const [result] = await db.query(
      'INSERT INTO companies (name, industry, size, contact_name, notes) VALUES (?, ?, ?, ?, ?)',
      [name, industry || null, size || null, contact_name || null, notes || null]
    );
    const [rows] = await db.query('SELECT * FROM companies WHERE id = ?', [result.insertId]);
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/companies/:id', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM companies WHERE id = ?', [req.params.id]);
    if (!rows.length) return res.status(404).json({ error: 'Not found' });
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Assessments ───────────────────────────────────────────────────────────────
app.post('/api/assessments', async (req, res) => {
  const { answers, score, stage, stageLabel, recommendedPages, company_id } = req.body;
  try {
    const db = await getPool();
    const [result] = await db.query(
      'INSERT INTO assessments (answers, score, stage, stage_label, recommended_pages, company_id) VALUES (?, ?, ?, ?, ?, ?)',
      [JSON.stringify(answers), score, stage, stageLabel, JSON.stringify(recommendedPages), company_id || null]
    );
    res.json({ id: result.insertId, score, stage, stageLabel, recommendedPages });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/assessments/:id', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM assessments WHERE id = ?', [req.params.id]);
    if (!rows.length) return res.status(404).json({ error: 'Not found' });
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── ROI ───────────────────────────────────────────────────────────────────────
app.post('/api/roi', async (req, res) => {
  const {
    roleName, hoursPerTask, frequencyPerMonth, hourlyRate,
    aiUpliftPct, toolCostMonthly, annualSaving, paybackMonths, roi24m, roi36m, company_id,
  } = req.body;
  try {
    const db = await getPool();
    const [result] = await db.query(
      `INSERT INTO roi_calculations
       (role_name, hours_per_task, frequency_per_month, hourly_rate,
        ai_uplift_pct, tool_cost_monthly, annual_saving, payback_months, roi_24m, roi_36m, company_id)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [roleName, hoursPerTask, frequencyPerMonth, hourlyRate,
       aiUpliftPct, toolCostMonthly, annualSaving, paybackMonths, roi24m, roi36m, company_id || null]
    );
    res.json({ id: result.insertId });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/roi/models', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM roi_models ORDER BY id');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Enterprise Functions ──────────────────────────────────────────────────────
app.get('/api/enterprise/functions', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM enterprise_functions ORDER BY sort_order');
    const parsed = rows.map(r => ({ ...r, uses: typeof r.uses === 'string' ? JSON.parse(r.uses) : r.uses }));
    res.json(parsed);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.put('/api/enterprise/functions/:id', async (req, res) => {
  const { id } = req.params;
  const { name, icon_name, color, maturity, stat, uses } = req.body;
  if (!name || !Array.isArray(uses)) return res.status(400).json({ error: 'name and uses (array) are required' });
  try {
    const db = await getPool();
    await db.query(
      `UPDATE enterprise_functions SET name=?, icon_name=?, color=?, maturity=?, stat=?, uses=? WHERE id=?`,
      [name, icon_name, color, maturity, stat, JSON.stringify(uses), id]
    );
    const [[row]] = await db.query('SELECT * FROM enterprise_functions WHERE id=?', [id]);
    if (!row) return res.status(404).json({ error: 'Not found' });
    res.json({ ...row, uses: typeof row.uses === 'string' ? JSON.parse(row.uses) : row.uses });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Server network info (for QR code LAN URL) ────────────────────────────────
app.get('/api/server-ip', (req, res) => {
  // LAN_IP env var takes priority — set it in .env to a fixed LAN address
  // so the QR code always points to the right host regardless of which
  // network interface the server happens to enumerate first.
  const envIp = process.env.LAN_IP;
  let ips;
  if (envIp) {
    ips = [envIp];
  } else {
    const ifaces = os.networkInterfaces();
    ips = Object.values(ifaces).flat()
      .filter(i => i.family === 'IPv4' && !i.internal)
      .map(i => i.address);
  }
  const origin = req.headers.origin || '';
  const frontendPort = origin.match(/:(\d+)/)?.[1] || '3001';
  res.json({ ips, frontendPort: Number(frontendPort) });
});

// ── Lab: Database Platforms ───────────────────────────────────────────────────
app.get('/api/lab/database-platforms', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM database_platforms ORDER BY sort_order');
    const parsed = rows.map(r => ({
      ...r,
      screenshot_urls: typeof r.screenshot_urls === 'string' ? JSON.parse(r.screenshot_urls) : r.screenshot_urls,
      features:        typeof r.features === 'string'        ? JSON.parse(r.features)        : r.features,
      limitations:     typeof r.limitations === 'string'     ? JSON.parse(r.limitations)     : r.limitations,
      tags:            typeof r.tags === 'string'             ? JSON.parse(r.tags)            : r.tags,
    }));
    res.json(parsed);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Lab: Gallery ─────────────────────────────────────────────────────────────

// Upload image
app.post('/api/lab/gallery', upload.single('file'), async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ error: 'No file provided' });
    const { originalname, mimetype, buffer, size } = req.file;
    const name = req.body.name || originalname;
    const db = await getPool();
    const [result] = await db.query(
      'INSERT INTO lab_gallery (name, mime_type, file_data, file_size) VALUES (?, ?, ?, ?)',
      [name, mimetype, buffer, size]
    );
    res.json({ id: result.insertId, name, mime_type: mimetype, file_size: size, comment: '', created_at: new Date().toISOString() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// List gallery (no binary data)
app.get('/api/lab/gallery', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query(
      'SELECT id, name, mime_type, file_size, comment, created_at, updated_at FROM lab_gallery ORDER BY created_at DESC'
    );
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Serve image binary
app.get('/api/lab/gallery/:id/image', async (req, res) => {
  try {
    const db = await getPool();
    const [[row]] = await db.query('SELECT mime_type, file_data FROM lab_gallery WHERE id = ?', [req.params.id]);
    if (!row) return res.status(404).json({ error: 'Not found' });
    res.set('Content-Type', row.mime_type);
    res.set('Cache-Control', 'public, max-age=86400');
    res.send(row.file_data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Update name / comment
app.put('/api/lab/gallery/:id', async (req, res) => {
  try {
    const { name, comment } = req.body;
    const db = await getPool();
    if (name !== undefined) await db.query('UPDATE lab_gallery SET name = ? WHERE id = ?', [name, req.params.id]);
    if (comment !== undefined) await db.query('UPDATE lab_gallery SET comment = ? WHERE id = ?', [comment, req.params.id]);
    const [[row]] = await db.query(
      'SELECT id, name, mime_type, file_size, comment, created_at, updated_at FROM lab_gallery WHERE id = ?',
      [req.params.id]
    );
    res.json(row || { error: 'Not found' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Delete
app.delete('/api/lab/gallery/:id', async (req, res) => {
  try {
    const db = await getPool();
    await db.query('DELETE FROM lab_gallery WHERE id = ?', [req.params.id]);
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }

// Replace image binary (used by editor save)
});
app.patch('/api/lab/gallery/:id/image', upload.single('file'), async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ error: 'No file provided' });
    const { mimetype, buffer, size } = req.file;
    const db = await getPool();
    await db.query(
      'UPDATE lab_gallery SET file_data = ?, file_size = ?, mime_type = ? WHERE id = ?',
      [buffer, size, mimetype, req.params.id]
    );
    res.json({ ok: true, id: Number(req.params.id), file_size: size, mime_type: mimetype });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Lab: Excalidraw Workspace ─────────────────────────────────────────────────

// List drawings (no scene_data — metadata only for sidebar)
app.get('/api/lab/excalidraw', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query(
      'SELECT id, name, thumbnail, created_at, updated_at FROM lab_excalidraw ORDER BY updated_at DESC'
    );
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Get single drawing with full scene data
app.get('/api/lab/excalidraw/:id', async (req, res) => {
  try {
    const db = await getPool();
    const [[row]] = await db.query(
      'SELECT id, name, scene_data, thumbnail, created_at, updated_at FROM lab_excalidraw WHERE id = ?',
      [req.params.id]
    );
    if (!row) return res.status(404).json({ error: 'Not found' });
    res.json({ ...row, scene_data: row.scene_data ? JSON.parse(row.scene_data) : null });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Create new drawing
app.post('/api/lab/excalidraw', async (req, res) => {
  try {
    const { name = 'Untitled Drawing', scene_data, thumbnail } = req.body;
    const db = await getPool();
    const [result] = await db.query(
      'INSERT INTO lab_excalidraw (name, scene_data, thumbnail) VALUES (?, ?, ?)',
      [name, scene_data ? JSON.stringify(scene_data) : null, thumbnail || null]
    );
    const [[row]] = await db.query(
      'SELECT id, name, thumbnail, created_at, updated_at FROM lab_excalidraw WHERE id = ?',
      [result.insertId]
    );
    res.json(row);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Update drawing (name, scene_data, thumbnail)
app.put('/api/lab/excalidraw/:id', async (req, res) => {
  try {
    const { name, scene_data, thumbnail } = req.body;
    const db = await getPool();
    if (name !== undefined)       await db.query('UPDATE lab_excalidraw SET name = ? WHERE id = ?', [name, req.params.id]);
    if (scene_data !== undefined) await db.query('UPDATE lab_excalidraw SET scene_data = ? WHERE id = ?', [JSON.stringify(scene_data), req.params.id]);
    if (thumbnail !== undefined)  await db.query('UPDATE lab_excalidraw SET thumbnail = ? WHERE id = ?', [thumbnail, req.params.id]);
    const [[row]] = await db.query(
      'SELECT id, name, thumbnail, created_at, updated_at FROM lab_excalidraw WHERE id = ?',
      [req.params.id]
    );
    res.json(row || { error: 'Not found' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Delete drawing
app.delete('/api/lab/excalidraw/:id', async (req, res) => {
  try {
    const db = await getPool();
    await db.query('DELETE FROM lab_excalidraw WHERE id = ?', [req.params.id]);
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Planning doc ─────────────────────────────────────────────────────────────
app.get('/api/planning', async (req, res) => {
  try {
    const db = await getPool();
    const [[row]] = await db.query('SELECT content, updated_at FROM planning_doc ORDER BY id LIMIT 1');
    res.json(row || { content: '', updated_at: null });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.put('/api/planning', async (req, res) => {
  try {
    const { content } = req.body;
    const db = await getPool();
    const [[{ pd_count }]] = await db.query('SELECT COUNT(*) AS pd_count FROM planning_doc');
    if (pd_count === 0) {
      await db.query('INSERT INTO planning_doc (content) VALUES (?)', [content]);
    } else {
      await db.query('UPDATE planning_doc SET content = ? ORDER BY id LIMIT 1', [content]);
    }
    const [[row]] = await db.query('SELECT content, updated_at FROM planning_doc ORDER BY id LIMIT 1');
    res.json(row);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── PDF Lab ───────────────────────────────────────────────────────────────────
const pdfUpload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 50 * 1024 * 1024 },
  fileFilter: (req, file, cb) => {
    cb(null, file.mimetype === 'application/pdf');
  },
});

// Upload a PDF
app.post('/api/lab/pdf/upload', pdfUpload.single('pdf'), async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ error: 'No PDF file provided' });
    const id = uuidv4();
    const db = await getPool();
    await db.query(
      'INSERT INTO pdf_files (id, original_name, stored_name, size, file_data) VALUES (?, ?, ?, ?, ?)',
      [id, req.file.originalname, req.file.originalname, req.file.size, req.file.buffer]
    );
    res.json({ id, original_name: req.file.originalname, size: req.file.size });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// List all PDFs
app.get('/api/lab/pdf/files', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT * FROM pdf_files ORDER BY created_at DESC');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Serve original PDF
app.get('/api/lab/pdf/files/:id/raw', async (req, res) => {
  try {
    const db = await getPool();
    const [[file]] = await db.query('SELECT original_name, file_data FROM pdf_files WHERE id = ?', [req.params.id]);
    if (!file || !file.file_data) return res.status(404).json({ error: 'Not found' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `inline; filename="${file.original_name}"`);
    res.send(file.file_data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Delete a PDF and its annotations
app.delete('/api/lab/pdf/files/:id', async (req, res) => {
  try {
    const db = await getPool();
    const [[file]] = await db.query('SELECT id FROM pdf_files WHERE id = ?', [req.params.id]);
    if (!file) return res.status(404).json({ error: 'Not found' });
    await db.query('DELETE FROM pdf_annotations WHERE pdf_id = ?', [req.params.id]);
    await db.query('DELETE FROM pdf_files WHERE id = ?', [req.params.id]);
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Get annotations for a PDF
app.get('/api/lab/pdf/files/:id/annotations', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query(
      'SELECT * FROM pdf_annotations WHERE pdf_id = ? ORDER BY created_at ASC',
      [req.params.id]
    );
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Save an annotation
app.post('/api/lab/pdf/files/:id/annotations', async (req, res) => {
  try {
    const { type, page_index, x, y, width, height, color, content, quoted_text } = req.body;
    const db = await getPool();
    const [result] = await db.query(
      `INSERT INTO pdf_annotations (pdf_id, type, page_index, x, y, width, height, color, content, quoted_text)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [req.params.id, type, page_index ?? 0, x ?? 0, y ?? 0, width ?? 0, height ?? 0,
       color ?? 'yellow', content ?? '', quoted_text ?? '']
    );
    const [[row]] = await db.query('SELECT * FROM pdf_annotations WHERE id = ?', [result.insertId]);
    res.json(row);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Delete an annotation
app.delete('/api/lab/pdf/annotations/:id', async (req, res) => {
  try {
    const db = await getPool();
    await db.query('DELETE FROM pdf_annotations WHERE id = ?', [req.params.id]);
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Download PDF with annotations embedded via pdf-lib
app.get('/api/lab/pdf/files/:id/download', async (req, res) => {
  try {
    const db = await getPool();
    const [[file]] = await db.query('SELECT original_name, file_data FROM pdf_files WHERE id = ?', [req.params.id]);
    if (!file || !file.file_data) return res.status(404).json({ error: 'Not found' });

    const [annotations] = await db.query(
      'SELECT * FROM pdf_annotations WHERE pdf_id = ? ORDER BY page_index, created_at',
      [req.params.id]
    );

    const pdfDoc = await PDFDocument.load(file.file_data);
    const pages = pdfDoc.getPages();

    for (const ann of annotations) {
      const pageIdx = ann.page_index;
      if (pageIdx >= pages.length) continue;
      const page = pages[pageIdx];
      const { width: pw, height: ph } = page.getSize();

      // Convert % coords (top-left origin) → PDF points (bottom-left origin)
      const pdfX  = (ann.x / 100) * pw;
      const pdfY  = ph - ((ann.y + ann.height) / 100) * ph;
      const pdfW  = (ann.width / 100) * pw;
      const pdfH  = (ann.height / 100) * ph;

      if (ann.type === 'highlight') {
        const annotObj = pdfDoc.context.obj({
          Type:       PDFName.of('Annot'),
          Subtype:    PDFName.of('Highlight'),
          Rect:       [pdfX, pdfY, pdfX + pdfW, pdfY + pdfH],
          QuadPoints: [pdfX, pdfY + pdfH, pdfX + pdfW, pdfY + pdfH, pdfX, pdfY, pdfX + pdfW, pdfY],
          C:          [1, 0.85, 0],
          Contents:   PDFString.of(ann.quoted_text || ''),
          F:          PDFNumber.of(4),
        });
        const ref = pdfDoc.context.register(annotObj);
        const existing = page.node.get(PDFName.of('Annots'));
        if (existing) { existing.push(ref); }
        else { page.node.set(PDFName.of('Annots'), pdfDoc.context.obj([ref])); }
      }

      if (ann.type === 'note') {
        const noteX = pdfX, noteY = pdfY;
        const annotObj = pdfDoc.context.obj({
          Type:     PDFName.of('Annot'),
          Subtype:  PDFName.of('Text'),
          Rect:     [noteX, noteY, noteX + 20, noteY + 20],
          Contents: PDFString.of(ann.content || ''),
          Name:     PDFName.of('Comment'),
          F:        PDFNumber.of(4),
        });
        const ref = pdfDoc.context.register(annotObj);
        const existing = page.node.get(PDFName.of('Annots'));
        if (existing) { existing.push(ref); }
        else { page.node.set(PDFName.of('Annots'), pdfDoc.context.obj([ref])); }
      }
    }

    const modifiedBytes = await pdfDoc.save();
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="annotated-${file.original_name}"`);
    res.send(Buffer.from(modifiedBytes));
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Get Fabric.js canvas JSON for all pages of a file
app.get('/api/lab/pdf/files/:id/fabric', async (req, res) => {
  try {
    const db = await getPool();
    const [rows] = await db.query('SELECT pages_json FROM pdf_fabric_data WHERE file_id = ?', [req.params.id]);
    if (!rows.length) return res.json({});
    res.json(JSON.parse(rows[0].pages_json || '{}'));
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// Save Fabric.js canvas JSON (upsert)
app.put('/api/lab/pdf/files/:id/fabric', async (req, res) => {
  try {
    const db = await getPool();
    const json = JSON.stringify(req.body.pages || {});
    await db.query(
      'INSERT INTO pdf_fabric_data (file_id, pages_json) VALUES (?, ?) ON DUPLICATE KEY UPDATE pages_json = ?, updated_at = NOW()',
      [req.params.id, json, json]
    );
    res.json({ ok: true });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// ── Start ─────────────────────────────────────────────────────────────────────
const PORT = process.env.PORT || 3002;
app.listen(PORT, async () => {
  console.log(`Backend running on port ${PORT}`);
  try {
    const db = await getPool();
    await runMigrations(db);
    console.log('Database migrations complete');
  } catch (err) {
    console.error('Migration error:', err.message);
  }
});
